# Generated by Django 3.0 on 2020-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemCode', models.CharField(max_length=50)),
                ('problemName', models.CharField(max_length=100)),
                ('problemStatement', models.TextField()),
                ('timeLimit', models.FloatField()),
                ('memoryLimit', models.IntegerField()),
                ('marking', models.IntegerField()),
                ('access', models.IntegerField()),
                ('creator', models.CharField(max_length=20)),
                ('editorialist', models.CharField(max_length=20)),
            ],
        ),
    ]
