# Generated by Django 2.1 on 2020-05-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestCode', models.CharField(max_length=20)),
                ('contestName', models.CharField(max_length=100)),
                ('startDay', models.IntegerField()),
                ('startMonth', models.IntegerField()),
                ('startYear', models.IntegerField()),
                ('startHours', models.IntegerField()),
                ('startMinutes', models.IntegerField()),
                ('durationHours', models.IntegerField()),
                ('durationMinutes', models.IntegerField()),
                ('rankingStyle', models.IntegerField()),
                ('questions', models.ManyToManyField(to='problems.Question')),
            ],
        ),
        migrations.CreateModel(
            name='IcpcMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.IntegerField()),
                ('verdict', models.IntegerField()),
                ('contestId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('questionId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problems.Question')),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IoiMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksAlloted', models.IntegerField()),
                ('contestId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('questionId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problems.Question')),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
