# Generated by Django 3.0 on 2020-05-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestCode', models.CharField(max_length=20)),
                ('contestName', models.CharField(max_length=100)),
                ('startDay', models.IntegerField()),
                ('startMonth', models.IntegerField()),
                ('startYear', models.IntegerField()),
                ('startHours', models.IntegerField()),
                ('startMinutes', models.IntegerField()),
                ('durationHours', models.IntegerField()),
                ('durationMinutes', models.IntegerField()),
                ('rankingStyle', models.IntegerField()),
                ('questions', models.ManyToManyField(to='problems.Question')),
            ],
        ),
    ]
