# Generated by Django 3.0 on 2020-05-17 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_question'),
        ('contest', '0002_icpcmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoiMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksAlloted', models.IntegerField()),
                ('contestId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('questionId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problems.Question')),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
