# Generated by Django 2.1 on 2020-05-24 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_playlistproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistCategory', models.CharField(max_length=200)),
                ('problemCount', models.IntegerField()),
                ('problems', models.ManyToManyField(to='problems.PlaylistProblems')),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
